import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainWrapper from "@/components/layout/MainWrapper";
import Footer from "@/components/layout/Footer";
import NavBar from "@/components/layout/NavBar";
import Providers from "@/redux/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Poo Diary",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <NavBar />
          <MainWrapper>{children}</MainWrapper>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
